### PR TITLE
Hoondev

### PR DESCRIPTION
**Pull request by hoonkim29**
- Fixed 'removing unneeded dates' in order to have full information available for us
- Added + processed COVID data (total_covid_cases & new_covid_cases)
- Integrated all variables into one df
- EDA on gas/unemployment/CPI/COVID vs approval_rating
- Built initial models (1,2&3) for each case we have discussed previously (m1: approval rating vs gas, m2: approval_rating vs gas + economic variables, m3: approval_rating vs gas + econ vars. + event vars.)
- For event variables, I took log transformation to both total_covid_cases and new_covid_cases, but feel free to suggest any other methods for transformation (polynomial transformation, etc.). Unemployment rate seems to have been excluded from the significant variable when we add both covid variables, but as you guys can see from the graph (new_covid_cases vs approval_rating), I don't see a very strong connection between new_covid_cases and approval_rating.
- + some minor style fix / efficiency related fix

Also added some comments to help y'all understand what kind of changes I made, but feel free to ping me for questions

I think we have enough grounds to get the report going, but we can definitely have more contents and exploration to do (i.e. combination of different variables + OVB analysis, etc.). I hope my codes help us move forward with more momentum.

### CODE REVIEW

**Comment by hecerinc** [comment]
Can you resolve the conflicts? Also I don't think we want to remove the RData file with the final data frame. Finally, I think we prefer `library` over `require` for importing libraries because `require` does not throw errors.

**Comment by hoonkim29** [comment]
> Can you resolve the conflicts? Also I don't think we want to remove the RData file with the final data frame. Finally, I think we prefer `library` over `require` for importing libraries because `require` does not throw errors.

`require` does not throw errors because it suggests all the missing libraries before execution whereas `library` does not. Do we really prefer `library` over `require`?

**Comment by hecerinc** [comment]
This only happens in RStudio, though, so I think it's less fragile if we use `library`

**Comment by hoonkim29** [comment]
> This only happens in RStudio, though, so I think it's less fragile if we use `library`

Both us and the readers are going to be using RStudio instead of plain R. I don't think that's an issue tbh.

**Comment by hoonkim29** [comment]
> > This only happens in RStudio, though, so I think it's less fragile if we use `library`
> 
> Both us and the readers are going to be using RStudio instead of plain R. I don't think that's an issue tbh.

I actually don't care, so if you insist we can use `library`

**Comment by hecerinc** [comment]
I think it makes slightly less fragile, yeah

**Comment by malay-patel** [comment]
Also, do not put the covid related code in the report file. You can stage it in a different file and we can bring it over when we add events. Also, please add discussions to the plots.

**Comment by hecerinc** [comment]
> Also, do not put the covid related code in the report file. You can stage it in a different file and we can bring it over when we add events. Also, please add discussions to the plots.

Actually that's what the clean_events.R file is for, so that's a good place for the COVID code :)

**Comment by malay-patel** [comment]
I was talking about the markdown file. I now noticed that you commented it. Also, this PR has conflict. I suggest you rebase and merge.

**Comment by hoonkim29** [comment]
> I was talking about the markdown file. I now noticed that you commented it. Also, this PR has conflict. I suggest you rebase and merge.

We can remove the commented out code if we end up not doing the events section. Not sure why we want to remove it right now when it won't print when we knit it?

**Comment by malay-patel** [comment]
> > I was talking about the markdown file. I now noticed that you commented it. Also, this PR has conflict. I suggest you rebase and merge.
> 
> We can remove the commented out code if we end up not doing the events section. Not sure why we want to remove it right now when it won't print when we knit it?

No, I am not asking to remove. I said, I am ok with this being there. We can clean up later. I mistook it earlier, but then later saw that it was commented which is fine.

**Pull request merged**
